sudo: required
services:
 - docker
before_install:
 - docker build -f Dockerfile.dev . -t toska29/docker-react
script:
 - docker run -e CI=true toska29/docker-react npm run test
deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: "frontend"
 env: "Frontend-env"
 bucket_name: "elasticbeanstalk-us-east-1-467726232621"
 bucket_path: "frontend"
 on:
  branch: main
access_key_id: "$AWS_ACCESS_KEY" 
secret_access_key: "$AWS_SECRET_KEY"